name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Zsh
        run: |
          sudo apt-get update
          sudo apt-get install zsh

      - name: Create a symbolic link to `.zshrc`
        run: ln -s $(pwd)/.zshrc $HOME/.zshrc

      - name: Read the `.zshrc` file
        run: zsh -ex .zshrc
